### PR TITLE
Set intent modal overflow to 'hidden' to preserve border radius

### PR DESCRIPTION
**Pull request by gregorylegarec**

### CODE REVIEW

**Comment by ptbrowne** [comment]
What is your problem exactly ? Do you have a reproducing case ? There is a overflowHidden property that can be set on the modal. Would it solve your problem ?

**Comment by gregorylegarec** [comment]
@ptbrowne Here's an example of an intent to Collect into a intent modal. The border should be rounded.

capture d ecran 2018-05-15 a 19 57 08

An alternative to setting `overflow: hidden` directly on modal is maybe to set it on `.intentModal` class instead. What do you think ? Or event force `overflowHidden` prop to `true` on intent modals ?

**Comment by gregorylegarec** [comment]
Plot twist : it isn't.

capture d ecran 2018-05-15 a 22 13 12

**Comment by gregorylegarec** [comment]
Second plot twist : the scrollbars seem to be a regression in cozy-ui. An investigation is ongoing.

**Comment by gregorylegarec** [comment]
Investigation concluded to a deprecated local version of Collect, which was displaying the scrollbars.

I updated my commit to only add `overflowHidden` on every `<IntentModal />`.

**Pull request merged**
