### PR TITLE
chore: use commitlint to ensure all commit messages are valid

### PR DESCRIPTION
**Pull request by drazik**
Using [commitlint](https://github.com/marionebl/commitlint) and [husky](https://github.com/typicode/husky), we ensure that the commit messages are well formatted. The rules are the one from [Conventional Commits](https://conventionalcommits.org/), that we already follow.

Failing : 

image

Success : 

image

### CODE REVIEW

**Comment by ptbrowne** [comment]
Can this be done before push instead of at each commit ?

**Comment by gregorylegarec** [comment]
Does it handle correctly the cute emojis we are using as prefix ? 🌻

**Comment by drazik** [comment]
@ptbrowne I don't know if it's possible, since `commitlint` just take a commit message as parameter and returns if it's well formed or not. I don't know if  we can get all commit messages in a `prepush` hook. So I asked here : https://github.com/marionebl/commitlint/issues/361

**Comment by drazik** [comment]
After discussing it with @ptbrowne, the idea would be to get the commits between `branch` and `origin/branch` in a `prepush` hook and pass them all to `commitlint` in a loop. I will look at it and propose something :)

**Comment by ptbrowne** [comment]
Thanks Cyrille, that's great !

**Comment by drazik** [comment]
I got an answer on the issue on commitlint : https://github.com/marionebl/commitlint/issues/361#issuecomment-394083870

I still have some investigation to do, because : 

* What happen if there's no remote branch for the local branch we are going to push ? We can look for a common commit in the tree, and lint the commit messages between this one and `HEAD`
* What happens if we changed the history and want to push force ? We shouldn't check the remote branch anymore since we are going to overwrite it completely

So instead of linting from `origin/branch`, maybe we should always lint from the common ancestor, to `HEAD` ?

**Comment by ptbrowne** [comment]
> But we need to find a way to find the commit at which our branch derived.

`git merge-base HEAD master`

**Pull request merged**
