### PR TITLE
feat: Button can render with a different Tag [breaking]

### PR DESCRIPTION
**Pull request by ptbrowne**
It is useful for a Button to render with a different tag.

Another solution for #484 that does not extend the API of Cozy UI.

For example if you want a Button to render with a NavLink : 

```
<Button tag={NavLink} to='/toto' />
```

It is a breaking change since `<AsButton />` is removed.

### CODE REVIEW

**Comment by gregorylegarec** [comment]
Great, I love it. 👍
And it simpler that the pseudo-HOC `<AsButton />`.
I am not familiar with passing components as props, but now I'll use this pattern.


Does the use of `{...restProps}` fit well with PropTypes validation ?

**Comment by ptbrowne** [comment]
> Does the use of {...restProps} fit well with PropTypes validation ?

Props passed with `...restProps` are validated with PropTypes. Was it your question ?

**Comment by gregorylegarec** [comment]
@ptbrowne In your example you're passing a `to` property to pass it to the `<NavLink />` element. As I am not yet very familiar with PropTypes mechanism, is it ok from a React point of view, if this property `to` is not declared as a `<Button />`'s PropType ?

**Comment by ptbrowne** [comment]
Yes it's OK. React does not emit any warning if a property is passed that is not declared in the PropTypes.

**Pull request merged**
