### PR TITLE
Add remaining time to individual uploads

### PR DESCRIPTION
**Pull request by ptbrowne**
Add remaining time next to progress bars.

- Only shown on desktop
- This component is only used in Drive but it should possible to use in Photo
- Speed is not shown, I chose this not to clutter the interface too much

https://ptbrowne.github.io/cozy-ui/react/#/UploadQueue

image

cc @joel-costa

### CODE REVIEW

**Comment by y-lohse** [comment]
The changes LGTM but visually, if we don't use the remaining time, the treshold bar doesn't go all the way to the left. Is that intended? Are we sure that we'll always have the download speed displayed?

Capture d'écran 2020-03-30 10 30 47

**Comment by ptbrowne** [comment]
It's intended on my part but I did not check with joel yet, this is why I pinged him :). I used a narrower progress bar not to have too much visual clutter.

**Comment by y-lohse** [comment]
@ptbrowne can you let me know when the code is ready for a second review?

**Comment by ptbrowne** [comment]
It's ok now.

**Pull request merged**
