### PR TITLE
fix: BottomSheet no longer opens fully

### PR DESCRIPTION
**Pull request by Merkur39**
Moved the contact async fetch in the Qualification Panel to the FooterContent parent, this prevents `mui-bottom-sheet` from miscalculating one of its style variables.

Demo: https://merkur39.github.io/cozy-ui/react/#!/Viewer/1

### CODE REVIEW

**Comment by Merkur39** [comment]
[🐛 Régression Viewer](https://trello.com/c/YMhlRg3Z/820-%F0%9F%90%9B-r%C3%A9gression-viewer)

**Comment by Ldoppea** [comment]
Seems like you are introducing a specific context (`contacts`) in a generic component (`viewer`). I don't know all the context, but this seems not to be ideal. Can you describe why this contact list is needed?

**Comment by Ldoppea** [comment]
Also your demo link is targeting the prod demo, shouldn't it be targeting your fork?

**Comment by Merkur39** [comment]
> Seems like you are introducing a specific context (`contacts`) in a generic component (`BottomSheetContent`). I don't know all the context, but this seems not to be ideal. Can you describe why this contact list is needed?

The Qualification block can contain the ID of the associated contact(s)
Fetch these contacts allows to display their name

**Review by JF-Cozy — APPROVED** [review]

**Pull request merged**
