### PR TITLE
feat: Deprecated children and added label & icon in Button

### PR DESCRIPTION
**Pull request by GoOz**
In order to have more control over the rendering of the basic usage of Button, I added two props `icon` and `label`. That way you can easily have a button with single text, icon+text or single icon.
You don't have to build those kind of buttons by yourself by sending the component the children node you need. 
That being said, you still can choose to send node children but you may have to add your own style if it doesn't render as you wish.

### CODE REVIEW

**Comment by ptbrowne** [comment]
I've started a codeshift to make the transition easy, I think it would be good to add it to the release notes.

Related comment on the issue : https://github.com/cozy/cozy-ui/issues/338#issuecomment-365986765

To easy the transition path, jscodeshift could be used ✨ 🎩

http://astexplorer.net/#/gist/cc94c9c4cc446d1958729300581bb250/2daaa0365e0424e191250f888704b1d9fc551fe9

**Comment by ptbrowne** [comment]
Ping ^

**Comment by GoOz** [comment]
I don't think I quite understand what you want me to do here. :/

**Comment by ptbrowne** [comment]
I added the mention : https://github.com/cozy/cozy-ui/pull/357/commits/d932f1f82ca8d266e05e4d8cee6e9aba98504b8e

**Comment by GoOz** [comment]
Aaaah ok, my bad. That was just it. Thanks.

**Pull request merged**
