### PR TITLE
Add xsmall modal size

### PR DESCRIPTION
**Pull request by CPatchane**
An new size with 24rem as width
Deployed on https://cpatchane.github.io/cozy-ui/react/#modal

### CODE REVIEW

**Comment by ptbrowne** [comment]
What's up with the cross ?



I thought we were going responsive, the sizes of the modal do not seem responsive ? Maybe an issue to open ?

LGTM otherwise but it'd be nice if the cross was fixed since we are working on modals.

**Comment by CPatchane** [comment]
Locally watching I don't have any issue with the cross :/
Screenshot 2019-04-23 at 16 48 59

**Comment by GoOz** [comment]
Yeah that's an issue occuring on styleguidist sometimes. It's an issue related to CSS order, not to this PR.

**Comment by GoOz** [comment]
> To be perfectly honest, I have the feeling that it should be the content that should dictate the size of these modals.

I don't agree. The container should set the available space for a given content and this content will naturally use all this available space. 
Also I don't think this is really relevant to this PR.

**Pull request merged**
