### PR TITLE
feat: Update colors

### PR DESCRIPTION
**Pull request by GoOz**
**Updated colors:**
- puertoRico #0DCBCF #0DCBCF
- zircon #F5FAFF #F5FAFF

**Added colors:**
- lavender #C2ADF4 #C2ADF4
- seafoamGreen #3DA67E #3DA67E

### CODE REVIEW

**Comment by GoOz** [comment]
[(XS) Couleurs cozy-UI](https://trello.com/c/O9ws9k79/664-xs-couleurs-cozy-ui)

**Comment by gregorylegarec** [comment]
What those colors are for ?

**Comment by GoOz** [comment]
> What those colors are for ?

I don't remember… I'm pretty sure it's for upcoming stuffs
ping @Claiw

**Comment by Claiw** [comment]
the two last added colors was added because we missed two colors for avatar in contacts, but they were never added to the cozy-ui

**Comment by GoOz** [comment]
Oh so I should add them to the avatar then.

**Pull request merged**
