### PR TITLE
fix: Layout issue on iPhone X

### PR DESCRIPTION
**Pull request by Crash--**
This fix our layout issue with Drive on an iPhone X. 

See https://trello.com/c/IY5dJyDv/367-iphone-x-adaptations

### CODE REVIEW

**Comment by Crash--** [comment]
I followed this article : https://blog.phonegap.com/displaying-a-phonegap-app-correctly-on-the-iphone-x-c4a85664c493 

You already have done a lot of works. Seems that this one was missing. 

I think we'll have some other changes to make in a near future, but we need to talk first ;)

**Comment by ptbrowne** [comment]
Naive question: is there a particular reason why this is not a `padding-bottom` like the other properties ?

LGTM.

**Comment by nono** [comment]
@Crash-- can we merge this PR?

**Comment by nono** [comment]
@Crash-- friendly reminder about this PR

**Pull request closed without merging**
