### PR TITLE
feat: Add u-lowercase class

### PR DESCRIPTION
**Pull request by doubleface**
This is needed in harvest for
https://github.com/cozy/cozy-libs/pull/1066

### CODE REVIEW

**Comment by JF-Cozy** [comment]
I think the doc's missing ?

**Comment by JF-Cozy** [comment]
Maybe we can refactor a bit all text-decoration to use something like `u-td-uppercase` like with `u-ta-` or `u-fw-` ?

**Review by Crash-- — APPROVED** [review]

**Comment by doubleface** [comment]
> I think the doc is missing ?

Right, here it is

**Comment by doubleface** [comment]
> Maybe we can refactor a bit all text-decoration to use something like `u-td-uppercase` like with `u-ta-` or `u-fw-` ?

Since u-uppercase already existed and since I do not know if it is widely used or not, I prefer not to change this for my first cozy-ui PR (I did some in 2015 but it does not count :-) )

**Pull request merged**
