### PR TITLE
feat(Viewer): On mobile, the title benefits well from the MidEllipsis

### PR DESCRIPTION
**Pull request by Merkur39**
Demo: https://merkur39.github.io/cozy-ui/react/#!/Extra/Viewer

Before:
Capture d’écran 2023-09-29 à 11 24 20

After:
Capture d’écran 2023-09-29 à 11 23 59

### CODE REVIEW

**Comment by Crash--** [comment]
can you add an exemple with the extension displayed?

**Comment by Merkur39** [comment]
> can you add an exemple with the extension displayed?

Here with MidEllipsis component:
Capture d’écran 2023-09-29 à 12 07 22

**Comment by Crash--** [comment]
> Here with MidEllipsis component:

And without? Because we don't want the caller to add this component, right?

**Comment by Merkur39** [comment]
> > Here with MidEllipsis component:
> 
> And without? Because we don't want the caller to add this component, right? Or we don't need to add it because it's already present somewhere?

The MidEllipsis component is well used within the Viewer, this does not impact the way of using the Viewer

**Review by Crash-- — APPROVED** [review]

**Pull request merged**
