### PR TITLE
feat: Add Em component

### PR DESCRIPTION
**Pull request by drazik**
~~This component wraps its children in a slight padding and a border. It's extracted from the new cozy-settings passphrase update form. (see https://github.com/cozy/cozy-settings/pull/269)~~

~~The name come from the discussion I had with Joël about the extraction of this component. He said « c'est comme un highlight ». If you have a better idea, please tell me :)~~

~~See https://drazik.github.io/cozy-ui/react/#!/HighlightedText/0~~

See https://github.com/cozy/cozy-ui/pull/1303#issuecomment-565116979

### CODE REVIEW

**Comment by ptbrowne** [comment]
Browsing on a thesaurus, I eventually came across Emphasis

image


I would prefer to have a Noun for the name of the components.

- [Emphasis](https://en.wikipedia.org/wiki/Emphasis_(typography)) seems good ?

<Em variant='bordered' /> ?

**Comment by drazik** [comment]
`<Em>` looks OK to me. @y-lohse any thoughts on this?

**Comment by drazik** [comment]
I just added `Em` to the Text components. See https://drazik.github.io/cozy-ui/react/#!/BaseText

**Comment by ptbrowne** [comment]
cc @joel-costa

**Comment by y-lohse** [comment]
Not against it and the implementation LGTM, but we also have Bold that serves a similar purpose… are we sure it's a highlight component? Do we have other use cases?

**Comment by ptbrowne** [comment]
> There is already Bold

This is why I think we can combine the two: `<Em variant='bold' />`

The composant is semantic and the variant is more about the design, like the Buttons.

**Comment by y-lohse** [comment]
Just checked with @joel-costa , the Settings Em blip should be a [`InlineCard`](https://docs.cozy.io/cozy-ui/react/#inlinecard), it's not a new component :)

**Comment by ptbrowne** [comment]
This could maybe be clearer in the styleguide. Emphasis components : Bold, InlineCard

**Comment by ptbrowne** [comment]
What should we do about this PR ?

**Comment by y-lohse** [comment]
IMO we can close it. @drazik ?

> This could maybe be made clearer in the styleguide. Emphasis components : Bold, InlineCard ?

If `inlineCard` is indeed used to highlight text, it makles sense to group it with the other text components 👍

**Comment by drazik** [comment]
I'm closing. I used InlineCard

**Pull request closed without merging**
