### PR TITLE
feat: add button

### PR DESCRIPTION
**Pull request by ptbrowne**

### CODE REVIEW

**Comment by GoOz** [comment]
I don't get it. What is it for? From what I understand you can only have `<button>` but not link `<a>` and you can have only one theme class when you're supposed to be able to add as many as you want if there are compatible.

**Comment by ptbrowne** [comment]
My goal here was to abstract the uses of classes and theming.

IMHO it's nicer to use

```
import { Button } from 'cozy-ui'

<Button theme={ 'regular' }>Salut</Button>
```

(regular should be default by the way ?)

than 

```
import classNames from 'classnames'

<button
    role='button'
    className={classNames('coz-btn', 'coz-btn--regular')}
>
    Contacter EDF
</button>
```

It is true that Button could take a `tag` attribute and that Proptypes would be nice.

**Comment by GoOz** [comment]
OK but we won't be able to use this component for specials buttons like the ones with icons.

**Comment by enguerran** [comment]
Why don't we? By creating the correct abstraction we can cover every button's usages. But to be able to do that, we have to list all kind of button's usage.
IMHO, it is an iterative work, and we could add this PR, then by refactoring projects' code, we could enrich the cozy-ui button component.

**Comment by ptbrowne** [comment]
> OK but we won't be able to use this component for specials buttons like the ones with icons.

What is the problem in this case ? I can modify the component.

**Comment by GoOz** [comment]
It's just that for a special button it needs several theme classes at the same time. I'm not saying it's not possible to do that, it's just that so far your component don't handle that case.

**Comment by ptbrowne** [comment]
True. Do you think it's worth going further in the <Button />-inside-cozy-ui direction or do we wait for an abstraction to emerge through the other apps ?

I can live well with the <Button /> inside my project but the first reason I made the PR was to have a discussion on this very issue :)

**Comment by gregorylegarec** [comment]
I agree with @enguerran, let's work by iteration, we can merge this PR right now without introducing any side effect, and iterate over it in the future to enhance the component.

**Comment by GoOz** [comment]
I'm not against merging it now and iterate later, i just wanted to point out that "issue".

**Comment by gregorylegarec** [comment]
Let's merge this, thanks @ptbrowne ! 👍

**Pull request merged**
