### PR TITLE
feat: Add I18n component :construction_worker:

### PR DESCRIPTION
**Pull request by kosssi**
With `cozy-ui/react/I18n` you can:
- import a I18n component : `import { I18n } from 'cozy-ui/react/I18n'`
- import default lang of cozy : `import { DEFAULT_LANG } from 'cozy-ui/react/I18n'` is `en`
- import translate décorator : `import { translate } from 'cozy-ui/react/I18n'`

## I18n component

A small example to use I18n component:

    <I18n lang={lang} dictRequire={(lang) => require(`./locales/${lang}`)}>

With context:

    const dictRequire = (lang, context) => context
      ? require(`./contexts/${context}/locales/${lang}`)
      : require(`./locales/${lang}`)
    ...
    <I18n context={context} lang={lang} dictRequire={dictRequire}>

With defaultLang:

    <I18n defaultLang='fr' lang={lang} dictRequire={(lang) => require(`./locales/${lang}`)}>

## Polyglot

In mobile context you can require directly polyglot with `import { _polyglot } from 'cozy-ui/react/I18n/translation')`

### CODE REVIEW

**Comment by enguerran** [comment]
So I could write a i18n component like this?

```jsx
<I18n lang='en' dictRequire={() => ({ title: 'My i18n applicaiton' })}>
    <h1>{t('title')}</h1>
</I18n>
```

**Comment by kosssi** [comment]
@enguerran Yes you can ;)

**Comment by ptbrowne** [comment]
I think it would be useful to have `moment` configured in this component.

**Comment by CPatchane** [comment]
@ptbrowne I think that we use `date-fns`  to avoid the too big `moment` library.

**Comment by ptbrowne** [comment]
Ah OK cool, I thought it was only for date and not time. Thank @CPatchane

**Comment by enguerran** [comment]
@kosssi Thank you, it would be useful to add a README.md with those samples in the I18n folder. To let future developers be aware of what we think obvious nowadays.

**Comment by enguerran** [comment]
Or a [StoryBook](https://github.com/storybooks/storybook) to explain with working examples

**Comment by ptbrowne** [comment]
StoryBook looks awesome ! I think it would be great for newcomers to have this.

**Comment by kosssi** [comment]
I test to add Storybook but is more more complicated than I thought.

**Pull request merged**
