### PR TITLE
feat: add ModalContent component

### PR DESCRIPTION
**Pull request by gregorylegarec**
Using this component helped me to avoid repeating CSS code from `.coz-modal-content`.

For example I have not been able to retrieve padding properties from `.coz-modal-content` class, like this :

```jsx
<Modal>
  <div className='{styles['coz-modal-content']}'>
     My content
  </div>
</Modal>
```
But now with this component I can do :

```jsx
<Modal>
  <ModalContent>
     My content
  </ModalContent>
</Modal>
```
And I got the correct padding, it works like a charm.

I think we could do the same for example the modal sections used in cozy-photos.

After discussing with @GoOz, to make CozyUI usable, I think we need to aim a "two flavor Cozy UI" :
 * One usable as a bootstrap CSS framework
 * Another one based on React Components libraries, usable as it, based on the CSS framework part.

This PR tries to make a first step for the React Components lib.

### CODE REVIEW

**Comment by CPatchane** [comment]
Will we never have the case when we don't want this class/padding?

**Comment by GoOz** [comment]
@CPatchane As `coz-modal` never has any left or right padding, I guess there will always have a need for a content wrapper.

**Comment by gregorylegarec** [comment]
@CPatchane When we don't want this class/padding, we do not use <ModalContent>. This component is absolutely not mandatory. Developers are still free tu use whatever markup they wants in their modals.

**Comment by enguerran** [comment]
My thoughts is to add it automatically: if we have a Modal's children, we add it. If not, we don't.
If one day, we accept that it is possible not to have the `coz-modal-content` class, then we will make it modular.

**Comment by gregorylegarec** [comment]
@enguerran Its is already the case, the modal in photos needs `coz-modal-section` class instead of `coz-modal-content`.

**Pull request merged**
