### PR TITLE
feat: Add AppTitle component

### PR DESCRIPTION
**Pull request by GoOz**
Added `AppTitle` component to be used in the cozy-bar.

It uses the basic rendering of `MainTitle` plus some alignment tweaks.
[Preview](https://gooz.github.io/cozy-ui/react/#apptitle)

Fixes: #820

### CODE REVIEW

**Comment by GoOz** [comment]
[(𝐌) [UI] Titre de l'application affiché dans la cozy-barre](https://trello.com/c/8Cu6w3ba/1289-%F0%9D%90%8C-ui-titre-de-lapplication-affich%C3%A9-dans-la-cozy-barre)

**Comment by Crash--** [comment]
Do you plan to do the changes in our apps? :D

**Comment by GoOz** [comment]
> Do you plan to do the changes in our apps? :D

Drive & Photos yes, because I used those to test it :) It's already done actually, I'm just waiting for the new release of UI.

**Comment by ptbrowne** [comment]
And banks ? :)

**Comment by GoOz** [comment]
> And banks ? :)

Not just yet, I have some emergencies to deal with first. But I can do it afterwards, if you're not in a hurry. :p

**Pull request merged**
