### PR TITLE
Button full width does not reset margins

### LINKED ISSUE #1561: Button props extension full should not set margin to 0
Prop `extension="full"` of `<Button />` component (https://docs.cozy.io/cozy-ui/react/#/Basics?id=button) set `margin: 0` in CSS, which replaces the behavior, for example, of the `<Stack />` component which defines vertical margins.

It's probably not a desired behavior.

### PR DESCRIPTION
**Pull request by ptbrowne**
Make button full width work with Stack component. Fixes #1561.

### CODE REVIEW

**Comment by Crash--** [comment]
Wondering if it's not a BC since it can have an hight impact if the consuming App is based on the fact that margin is set to 0, no?

**Comment by ptbrowne** [comment]
I am not sure it would be high impact, but I can put a breaking change mention here.

**Comment by JF-Cozy** [comment]
I kind of see it the other way around. In case we're not in `<Stack>`, we won't have a null vertical alignment. That's the breaking change, isn't it?

**Comment by ptbrowne** [comment]
I do not understand your question. Before, inside a Stack, the full width button does not respect what is told by its parent, since it resets the `margin-{top,bottom}: 0` whereas it only needs to reset the horizontal margins.

See https://github.com/cozy/cozy-ui/blob/master/stylus/components/button.styl#L72 where the button already sets the vertical margins to 0.

The breaking change is that now, if in a Stack, the full-width button will work "as expected", it will follow the margins given by its parent.

**Comment by JF-Cozy** [comment]
Okay, I didn't have the button case in mind.

**Review by JF-Cozy — APPROVED** [review]

**Comment by Crash--** [comment]
> The breaking change is that now, if in a Stack, the full-width button will work "as expected", it will follow the margins given by its parent.

Not just `Stack` Component. 

It'll close https://github.com/cozy/cozy-ui/issues/797

**Pull request merged**
