### PR TITLE
Chore/lint

### PR DESCRIPTION
**Pull request by GoOz**
⚠️ **TO  BE MERGED AFTER** #36 ⚠️ 

- [x] Adds configuration to match guidelines
- [x] Cleanup CSS so it matches guidelines

### CODE REVIEW

**Comment by m4dz** [comment]
Great! Shall we explicitely declares `error: false` statuses as it's the default value in config, or doing it only when we want to trigger an error seems to be sufficient?

**Comment by GoOz** [comment]
@m4dz Absolutely not, you're totally right. I was playing with the config and it was easier to use the "verbose" version of each option to do so. Now it should be cleaned as it is indeed redundant. Will do asap.

**Comment by m4dz** [comment]
@GoOz any news on it?

**Comment by GoOz** [comment]
@m4dz just did it. I had trouble finding some spare time to do it.
FYI there's still some warning about not respected depth limit, but ignore them, there's some heavy refactoring on the way.

**Comment by m4dz** [comment]
Woohooo \o/

**Pull request merged**
