### PR TITLE
feat: add explicitely One column layout

### PR DESCRIPTION
**Pull request by GoOz**
Added a One Column layout. Well it was already kinda here already but it's more explicit this way.

### CODE REVIEW

**Comment by GoOz** [comment]
[Ajouter un layout mono-colonne](https://trello.com/c/fWVp5jcG/69-ajouter-un-layout-mono-colonne)

**Comment by GoOz** [comment]
[Ajouter un layout mono-colonne](https://trello.com/c/fWVp5jcG/69-ajouter-un-layout-mono-colonne)

**Comment by GoOz** [comment]
[Ajouter un layout mono-colonne](https://trello.com/c/fWVp5jcG/69-ajouter-un-layout-mono-colonne)

**Comment by GoOz** [comment]
[Ajouter un layout mono-colonne](https://trello.com/c/fWVp5jcG/69-ajouter-un-layout-mono-colonne)

**Comment by y-lohse** [comment]
Code looks good, although I wonder about something. On very large screens, we don't want 100% of the width, so there should be a max-width somewhere. But maybe it should be in a separate wrapper?

**Comment by GoOz** [comment]
Exactly. If someone wants to build an app that would take 100% of the width available, I think it should be by default. But if you want your content to have a max-width then just add you own style to the wrapper of you content (or override the Layout's style).

**Comment by y-lohse** [comment]
Ok, that makes sense, thanks 👍

**Pull request merged**
