### PR TITLE
fix: export default button component

### PR DESCRIPTION
**Pull request by y-lohse**
Makes `import Button from 'cozy-ui/react/Button'` work!

### CODE REVIEW

**Comment by GoOz** [comment]
I may have missed something but why the need? and why just the Button component?

**Comment by ptbrowne** [comment]
It is already the case for Icon, Modal, etc... It should work because when you import the default of a module you should get something useful, not some undefined thing. Thanks @y-lohse

**Comment by GoOz** [comment]
Ok then but shouldn't we do the same for `<ButtonLink />`?

**Comment by ptbrowne** [comment]
In this case we would have to put `ButtonLink` in another file since you cannot have two default exports in the same file. I am not against splitting the two. For now you can do `import { ButtonLink } from 'cozy-ui/react/Button'`

**Comment by GoOz** [comment]
oh yeah that's right, only one default :P

**Pull request merged**
