### PR TITLE
fix: Remove margin-top on text when no title

### PR DESCRIPTION
**Pull request by GoOz**
Before:
Screenshot 2019-05-09 17 17 37

After:
Screenshot 2019-05-09 17 22 13

Preview: https://gooz.github.io/cozy-ui/react/#infos

### CODE REVIEW

**Comment by ptbrowne** [comment]
It feels a bit like a hack to need JS to do this. I read somewhere that to avoid this kind of problem, some people used only vertical padding in one direction. This way it is always the responsibility of the top element to add the margin-bottom.

Found the article : https://csswizardry.com/2012/06/single-direction-margin-declarations/

Should we start doing that ?

**Comment by y-lohse** [comment]
> I read somewhere that to avoid this kind of problem, some people used only spacing in one direction. This way it is always the responsibility of the top element to add the margin-bottom.

I haven't looked at this fix yet, but… [yes](https://github.com/cozy/cozy-ui/pull/953#pullrequestreview-232198039).

**Comment by y-lohse** [comment]
Also, can we please have the preview somewhere so we can play with it?

**Comment by GoOz** [comment]
> It feels a bit like a hack to need JS to do this. I read somewhere that to avoid this kind of problem, some people used only vertical padding in one direction. This way it is always the responsibility of the top element to add the margin-bottom.

I tend to do that myself, I guess it's doable without too much effort.

**Comment by GoOz** [comment]
> Also, can we please have the preview somewhere so we can play with it?

https://gooz.github.io/cozy-ui/react/#infos

**Comment by y-lohse** [comment]
> I tend to do that myself, I guess it's doable without too much effort.

Honestly I think it would be great for this component. Things look ok now, but I wasn't fond of the first conditional class, so building on top of that doesn't feel safe. It's also the second fix in short order for the same component, so a css do-over if it doesn't take too long would be helpful.

**Comment by GoOz** [comment]
As expected, it wasn't too much effort. I also updated the preview.

**Pull request merged**
