### PR TITLE
fix(Icon): Handle palette in <Icon />

### PR DESCRIPTION
**Pull request by CPatchane**
Be able to use the cozy-ui palette in this component like:

```jsx
<Icon icon="help" color="dodgerBlue" />
```

### CODE REVIEW

**Comment by ptbrowne** [comment]
Have you considered how would this work with themes ?

**Comment by CPatchane** [comment]
Thanks @nono 
For the theme I don't really know how our current palette mecanism will work with the theme so if a component use the palette it will be the same work/question for me.

**Comment by ptbrowne** [comment]
I am not sure this PR is necessary since one can `import` the palette in the app and use the color from the palette. I do not see the gain here.

**Comment by CPatchane** [comment]
Ok then let's close this PR and see if this need will come back. Thanks @ptbrowne 👍

**Pull request closed without merging**
