### PR TITLE
Feat/modal responsive buttons

### PR DESCRIPTION
**Pull request by GoOz**
Modal action buttons have a slight different behavior now.

No change on desktop but when reaching small screens (< 768px) buttons share the horizontal space and there's no room for one of them anymore, it wraps the buttons.

[Preview](https://gooz.github.io/cozy-ui/react/#!/Modal/15)

### CODE REVIEW

**Comment by GoOz** [comment]
[(𝐒) Modifier le comportement des boutons dans le footer des modales](https://trello.com/c/zjormRhJ/607-%F0%9D%90%92-modifier-le-comportement-des-boutons-dans-le-footer-des-modales)

**Comment by ptbrowne** [comment]
It's weird, I do not have the change at < 768px but at < 334px (weird breakpoint ?) 

333px

image


334

image

**Comment by GoOz** [comment]
@ptbrowne That's the point actually. 

Starting at 768px, buttons share equitably the available space with at least a 50% width each, on a single line, until one of them can't deal with the available space anymore and everything goes on column(-ish).

Try again by setting a button with a longer label, it will "break" sooner.

**Comment by ptbrowne** [comment]
Ah OK, I guessed I had misunderstood, it's clearer to me now 👍 LGTM

**Pull request merged**
